### PR TITLE
fix: Use correct offset when trimming unicode char

### LINKED ISSUE #330: Annotation is incorrectly offset when overly long source line that contains non-ASCII characters is elided
For additional context: https://github.com/rust-lang/rust/issues/132860.

Given the following setup:

```rs
use annotate_snippets::{AnnotationKind, Group, Level, Renderer, Snippet};

fn main() {
    /***** (A): ASCII only *****/
    // let source = "/*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/?";
    // let highlight = "?";

    /***** (B): non-ASCII prefix, ASCII highlight *****/
    // let source = "/*这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/?";
    // let highlight = "?";

    /***** (C): non-ASCII everything *****/
    // let source = "/*这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/好";
    // let highlight = "好";

    let start = source.find(&highlight).unwrap();
    let range = start..start + highlight.len();

    let group = Group::with_level(Level::ERROR).element(
        Snippet::source(source).annotation(AnnotationKind::Primary.span(range).label("label")),
    );
    eprintln!("{}", Renderer::styled().render(&[group]));
}
```

---

Case **(A)**: The annotation / highlight / underline / caret is correctly placed below the `?`:

```
  |
1 | ...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/?
  |                                                                 ^ label
```

Case **(B)**: The annotation / … / caret is incorrectly offset by +1 (points one past the `?`):

```
  |
1 | ... 是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/?
  |                                                                  ^ label
```

Case **(C)**: Similarly offset by +1 (1st `^` points at the 2nd half of `好`, 2nd `^` points into nothingness):

```
  |
1 | ... 是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/好
  |                                                                  ^^ label
```

> [!IMPORTANT]
> Your browser probably renders these labeled annotations "way off". If so, that's only because it renders the Hanzi characters with a "width" of <2 (however, it probably also depends on your system fonts) whereas terminal emulators conventionally render Hanzi characters using two "blocks".
>
> So, here's a screenshot of my terminal output to further clarify that it's a +1 offset only:
>
> Image
>
> Again, if your browser renders is like in the image below, don't be misled, only the terminal emulator's output matters!
>
> <details><summary>Click to expand image of my browser</summary>
> Image
> </details>

### Meta

I'm using annotate-snippets v0.11.5, git revision 74964e91d845e39fb549c4028452beffa7c6562b (i.e., latest master at the time of writing).

### PR DESCRIPTION
**Pull request by Muscraft**
#330 showed a few cases where `annotate-snippets` would annotate a line incorrectly when it tried to trim unicode characters. Two things caused this: 
- Not adjusting the [`left`](https://github.com/rust-lang/annotate-snippets-rs/blob/fd61af931f81936dcd4af9359c1ce961dbf564f3/src/renderer/render.rs#L1996) padding if it didn't match [`skipped`](https://github.com/rust-lang/annotate-snippets-rs/blob/fd61af931f81936dcd4af9359c1ce961dbf564f3/src/renderer/render.rs#L2001)
- Not skipping multi-byte chars when their width + `skipped` exceeded `left`.

This PR addresses both of those issues.

Before:
Screenshot From 2025-10-24 11-43-21

After:
Screenshot From 2025-10-24 11-42-53

<details>
  <summary>Test Script</summary>
  
  ```rust
  use annotate_snippets::{AnnotationKind, Group, Level, Renderer, Snippet};
  
  fn main() {
      /***** (A): ASCII only *****/
      let ascii_only_end = (
          "(A): ASCII only",
          "/*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/?",
          "?",
      );
  
      /***** (B): non-ASCII prefix, ASCII highlight *****/
      let non_ascii_pre_ascii_highlight_end = (
          "(B): non-ASCII prefix, ASCII highlight",
          "/*这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/?",
          "?",
      );
  
      /***** (C): non-ASCII everything *****/
      let non_ascii_end = (
          "(C): non-ASCII everything",
          "/*这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/好",
          "好",
      );
  
      /***** (D): non-ASCII everything, annotate middle *****/
      let non_ascii_middle = (
          "(D): non-ASCII everything, annotate middle",
          "/*这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽好。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。这是宽的。*/?",
          "好",
      );
      for (desc, source, highlight) in [
          ascii_only_end,
          non_ascii_pre_ascii_highlight_end,
          non_ascii_end,
          non_ascii_middle,
      ] {
          //println!("\n");
          let renderer = Renderer::styled();
  
          let start = source.find(highlight).unwrap();
          let range = start..start + highlight.len();
          let annotation = AnnotationKind::Primary.span(range.clone());
  
          let group_with_label = Group::with_level(Level::ERROR)
              .element(Snippet::source(source).annotation(annotation.clone().label("label")));
          println!("{desc}\n{}\n", renderer.render(&[group_with_label]));
  
          let group_no_label =
              Group::with_level(Level::ERROR).element(Snippet::source(source).annotation(annotation));
  
          println!("{}\n", renderer.render(&[group_no_label]));
      }
  }

  ```
  
</details>

fixes #330

### CODE REVIEW

File: tests/formatter.rs [hunk 1]
```diff
@@ -2937,7 +2937,7 @@ error: title
     assert_data_eq!(renderer.render(input), expected_ascii);
 
     let expected_unicode = str![[r#"
-error: title
+error: titlecompiler/rustc_errors
```
Comment (epage) [inline tests/formatter.rs]: does this commit pass on its own?  I'm not seeing the edit that would cause this output change (and ascii is unchanged)

**Review by epage — APPROVED** [review]
Feel free to merge once the commits are fixed

File: tests/formatter.rs (hunk 1 above)
Comment (Muscraft) [reply tests/formatter.rs]: That change shouldn't have been there. I'm not sure how I missed it.
