### PR TITLE
fix: Take Into<Cow> instead of &str

### LINKED ISSUE #200: Owned variants of APIs where &str is used
I've been using this crate for personal project of mine, and I've sometimes found myself wanting to do something like this this:

```rust
fn make_message(token: &Token) -> Message<'_> {
    Level::Error.header(format!("unhandled token `{}`", token.src))
        .[...]
}
```

For obvious reasons, this doesn't directly work. To make it work the error string has to be stored out of line elsewhere, but this isn't always convenient (at least, it isn't for my design). It would be easier if there was a variant of (at least some) of the APIs which accepts a `String` instead, and the fields internally store a `Cow<'src, 'str>` instead of a `&'src str`.

Incidentally, this also might help people who have use cases that would have wanted #101, since it would be easier to directly format into a `String` that is stored by the `Message`.

### PR DESCRIPTION
**Pull request by Muscraft**
Fixes #200

### CODE REVIEW

File: src/level.rs [hunk 1]
```diff
@@ -56,9 +57,9 @@ impl<'a> Level<'a> {
     /// not allowed to be passed to this function.
     ///
     /// </div>
-    pub fn text(self, text: Option<&'a str>) -> Level<'a> {
+    pub fn text(self, text: Option<impl Into<Cow<'a, str>>>) -> Level<'a> {
```
Comment (epage) [inline src/level.rs:60]: A place where `OptionCow` is unused

File: src/snippet.rs [hunk 2]
```diff
@@ -407,6 +411,38 @@ impl<'a> Origin<'a> {
...
 }
 
+impl<'a> From<Cow<'a, str>> for Origin<'a> {
+    fn from(origin: Cow<'a, str>) -> Self {
+        Self::new(origin)
+    }
+}
+
+#[derive(Debug)]
+pub struct OptionCow<'a>(Option<Cow<'a, str>>);
```
[the remark this answers is not in the document]
Comment (epage) [reply src/snippet.rs:421]: We use `Option<into Cow>` in places, like https://github.com/rust-lang/annotate-snippets-rs/pull/232/files#r2172869778

File: tests/formatter.rs [hunk 3]
```diff
@@ -2448,7 +2448,7 @@ fn secondary_title_no_level_text() {
         )
         .element(
             Level::NOTE
-                .text(None)
+                .text(None::<&str>)
```
Comment (epage) [inline tests/formatter.rs:2451]: Is this still needed?

Comment (Muscraft) [reply tests/formatter.rs:2451]: sadly yes

Comment (epage) [reply tests/formatter.rs:2451]: How come and then why does `OptionCow` exist?  I thought it was to bypass this problem

Comment (Muscraft) [reply tests/formatter.rs:2451]: `::<&str>` is needed because the type of `None` can't be inferred, as the `From` impl for `Option` is generic over `T: Into<Cow<'a, str>>`. This problem would still exist if we were to write out the different `From`. 

`OptionCow` exists to solve the more common case of passing in a literal without also needing to write `Some()`.

Comment (epage) [reply tests/formatter.rs:2451]: I have a way of solving this with `None` with a new type but I thought I had a way of solving this without `None` without any new types but my ideas aren't working and not finding any breadcrumbs (in clap I went from `impl Into<Option<&str>>` straight to the solution for `None`).
